apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: hello-web
  name: hello-svc
  namespace: hello-app
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello-web
  type: LoadBalancer
status:
  loadBalancer: {}
